language: python
python:
  - "2.6"
  - "2.7"

env:
  - DJANGO=django>=1.5,<=1.6 --use-mirrors
  - DJANGO=django>=1.4,<=1.5 --use-mirrors

install:
  - pip install $DJANGO
  
script: python setup.py test

notifications:
  email:
    - jklaiho@iki.fi

