language: python
python:
  - "2.6"
  - "2.7"

env:
  - DJANGO=django>=1.5,<=1.6
  - DJANGO=django>=1.4,<=1.5

install:
  - "pip install $DJANGO --use-mirrors"
  - "pip install ."
  
script: python setup.py test

